version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client:/app

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./server:/var/www/html
    environment:
      - APP_ENV=production
      - APP_KEY=your_app_key_here
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=your_database_name
      - MYSQL_USER=your_database_user
      - MYSQL_PASSWORD=your_database_password
      - MYSQL_ROOT_PASSWORD=your_database_root_password

volumes:
  db-data:
